---
- hosts: master
  roles:
    - role: master
  vars:
    atomic_master: 192.168.60.2
    etcd_master: 192.168.60.2
- hosts: node01
  roles:
    - role: node
  vars:
    primary_interface: "{{ ansible_enp0s8.ipv4.address }}"
    atomic_master: 192.168.60.2
    etcd_master: 192.168.60.2
