---
- name: Setup an Atomic OS Master
  hosts: atomic_test_nodes

  tasks:
  - name: Local Docker registry systemd unit file
    copy:
      src=files/local-registry.service
      dest=/etc/systemd/system/local-registry.service
      owner=root
      group=root
      mode=0644

  - name: ETCD Server
    lineinfile:
      dest=/etc/etcd/etcd.conf
      regexp='ETCD_LISTEN_CLIENT_URLS='
      line=ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"
