---
#  Setup an Atomic OS Master

- name: Make sure atomic is up to date
  command: /usr/bin/systemctl reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  sudo: false

notify:
- name: Create the local Docker registry
  docker:
    name: local-registry

- name: Change the SELinux context on the directory that docker created for our persistence volume.
  command: /usr/bin/chcon -Rvt svirt_sandbox_file_t /var/lib/local-registry

- name: Local Docker registry systemd unit file
  copy:
    src=files/local-registry.service
    dest=/etc/systemd/system/local-registry.service
    owner=root
    group=root
    mode=0644

- name: ETCD Server interface config
  lineinfile:
    dest=/etc/etcd/etcd.conf
    regexp='ETCD_LISTEN_CLIENT_URLS='
    line=ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"

- name: ETCD Server advertise config
  lineinfile:
    dest=/etc/etcd/etcd.conf
    regexp='ETCD_ADVERTISE_CLIENT_URLS='
    line=ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"
